### ISSUE TITLE
orderedKeys returns arrays with nil and this is a bad idea.

### ISSUE THREAD

**Issue by Ducasse** [Ducasse/Containers-OrderPreservingDictionary#1]
CTStandardOrderedDictionary orderedDictionaryABC orderedKeys

**Comment by SmiljanaKnezev** [comment]
This is because:
 CTStandardOrderedDictionary >> new
	^ self new: 10
This is the same in OrderedDictionary:
| dict |
	dict := OrderedDictionary new. 
	dict at: #A put: 'A'.
	dict at: #B put: 'B'.
	dict at: #C put: 'C'.
dict orderedKeys >>> #(#A #B #C nil nil nil nil nil nil nil)

Should the number 10 be replaced with 1?
 CTStandardOrderedDictionary >> new
	^ self new: 1

**Comment by guillep** [comment]
Hi @SmiljanaKnezev , the size of the dictionary is not necessarily an issue, because it will grow when we start adding things to the dictionary, and you will most of the times have empty buckets for elements. This is of cours an internal implementation issue of the dictionary.

The problem with `orderedKeys` is that it is exposing part of those internals. As a user I don't care if the dictionary has empty buckets for some kind of optimization or not. I want that `orderedKeys` returns a collection with only the keys. So maybe the method `orderedKeys` should hide the fact that there are empty buckets in the dictionary and filter them (with a `select:` for example?).
